### ISSUE TITLE
"Posted on" text shaddow issues on singular post views

### ISSUE THREAD

**Issue by dd32** [cameronjonesweb/wcbne17#30]
<img width="473" alt="screen shot 2017-03-21 at 3 45 43 pm" src="https://cloud.githubusercontent.com/assets/767313/24134072/8556b6d8-0e4d-11e7-8486-ad925bcd9076.png">

**Comment by cameronjonesweb** [comment]
We discussed this yesterday :)

@KawaiiHannah this also affects buttons in the content
![image](https://cloud.githubusercontent.com/assets/12673074/24141083/0818e5bc-0e6e-11e7-8720-45d1c0a3c232.png)

Also the number `7` doesn't play nicely
![image](https://cloud.githubusercontent.com/assets/12673074/24141138/39d730f4-0e6e-11e7-8eae-8fa50b19edb3.png)

**Comment by cameronjonesweb** [comment]
Looks like this was resolved in 50f2987700512c7475b90ee397c1454bd46bfa91
