### ISSUE TITLE
#comments is 4em tall without comments enabled

### ISSUE THREAD

**Issue by dd32** [cameronjonesweb/wcbne17#39]
Not sure if this is intentional, but the #comments div is 4em high, even without comments enabled.
Happy for this to be closed as "Lets call that a design feature".

eg https://2017.brisbane.wordcamp.org/sponsor/linux-australia/
<img width="1191" alt="screen shot 2017-03-23 at 10 53 54 am" src="https://cloud.githubusercontent.com/assets/767313/24227196/278e412c-0fb7-11e7-9cf9-7d05c6c5bac2.png">

**Comment by cameronjonesweb** [comment]
I thought I fixed that... we'll change the selector to only affect blog posts

**Comment by cameronjonesweb** [comment]
So... turns out I did fix it, I just didn't merge it
